Repository scipp/scipp, pull requests merged in 2020-11, with the labels that each got.

#1361 Better plot interface
  python/bind_data_access.h
  python/dataset.cpp
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller2d.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model1d.py
  python/src/scipp/plot/model2d.py
  python/src/scipp/plot/panel1d.py
  python/src/scipp/plot/panel3d.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot1d.py
  python/src/scipp/plot/plot2d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/profile.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/view.py
  python/src/scipp/plot/widgets.py
  python/tests/plot/test_plot_3d.py
  python/tests/test_dataset.py
Labels: visualization

#1371 Fix plots in docs
  python/src/scipp/plot/__init__.py
Labels: docs

#1373 Fix instrument view surface cut not triggering updates
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/view3d.py
Labels: bug, visualization

#1364 Plot numpy arrays and dicts
  python/src/scipp/compat/dict.py
  python/src/scipp/plot/plot.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
Labels: visualization

#1374 Various plot fixes
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/plot1d.py
  python/src/scipp/plot/plot2d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/view.py
  python/src/scipp/plot/widgets.py
Labels: visualization

#1375 Extend colorbar ends
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/plot2d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/tools.py
  python/src/scipp/runtime_config.py
Labels: visualization

#1378 Delay matplotlib import to avoid hard dependency
  python/src/scipp/plot/tools.py
Labels: CI, docs, visualization

#1387 Plot binned data
  docs/scipp-neutron/instrument-view.ipynb
  docs/tutorials/neutron-diffraction.ipynb
  docs/user-guide/binned-data.ipynb
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plot/dispatch.py
  python/src/scipp/plot/sciplot.py
  python/tests/plot/plot_helper.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_3d.py
  python/tests/plot/test_plot_nd.py
Labels: visualization

#1388 Cleanup and update docs
  core/element_array_view.cpp
  core/include/scipp/core/bucket_array_view.h
  core/include/scipp/core/element_array_view.h
  core/include/scipp/core/multi_index.h
  core/multi_index.cpp
  core/test/multi_index_test.cpp
  dataset/variable_instantiate_bucket_elements.cpp
  docs/developer/variable_implementation.rst
  docs/images/variable_classes.dia
  docs/images/variable_classes.svg
  variable/include/scipp/variable/apply.h
  variable/include/scipp/variable/bucket_model.h
  variable/include/scipp/variable/data_model.h
  variable/include/scipp/variable/transform.h
  variable/include/scipp/variable/variable.h
  variable/include/scipp/variable/variable_concept.h
  variable/include/scipp/variable/variable_factory.h
  variable/include/scipp/variable/visit.h
  variable/test/bucket_model_test.cpp
  variable/variable_instantiate_bucket_elements.cpp
Labels: docs

#1392 Fix double figures in docs
  docs/user-guide/binned-data.ipynb
  docs/visualization/customizing-figures.ipynb
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/sciplot.py
Labels: bug, docs, visualization

#1400 Better mpl api for plots
  docs/visualization/customizing-figures.ipynb
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot1d.py
  python/src/scipp/plot/plot2d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/sciplot.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_3d.py
Labels: visualization

#1404 Update to newer pybind
  CMake/pybind11.in
Labels: CI

#1418 Docs updates
  dataset/bin.cpp
  docs/_static/title-binning.png
  docs/_static/title-instrument-view.png
  docs/_static/title-masking.png
  docs/_static/title-plotting.png
  docs/_static/title-repr-html.png
  docs/_static/title-show.png
  docs/about/release-notes.rst
  docs/getting-started/overview.rst
  docs/getting-started/quick-start.ipynb
  docs/index.rst
  docs/user-guide/binned-data.rst
  docs/user-guide/binned-data/binned-data.ipynb
  docs/user-guide/binned-data/computation.ipynb
  docs/user-guide/binned-data/filtering.ipynb
  docs/user-guide/masking.ipynb
  docs/user-guide/reading-and-writing-files.ipynb
  docs/user-guide/slicing.ipynb
  docs/visualization/representations-and-tables.ipynb
Labels: docs

#1424 Fix widget backend not being enabled by default
  python/src/scipp/plot/__init__.py
  scipp-developer-no-mantid.yml
  scipp-developer.yml
Labels: bug, visualization

#1422 Fix links and add page explaining histogram/groupby/bin differences
  docs/index.rst
  docs/python-reference/api.rst
  docs/user-guide/binned-data.rst
  docs/user-guide/binned-data/histogramming-grouping-and-binning.ipynb
  docs/user-guide/reading-and-writing-files.ipynb
Labels: docs
