Repository scipp/scipp, pull requests merged in 2020-07, with the labels that each got.

#1231 Added a note telling users Mantid+Scipp can be installed on Windows
  docs/getting-started/installation.rst
Labels: docs

#1232 Use numpy instead of sc.min/max to find colorbar limits
  python/src/scipp/plot/tools.py
  python/tests/plot/test_plot_2d.py
Labels: visualization

#1198 2D plots with non-regular bins
  core/include/scipp/core/element_array_view.h
  dataset/test/rebin_test.cpp
  docs/about/release-notes.rst
  docs/visualization/customizing-figures.ipynb
  docs/visualization/plotting-1d-data.ipynb
  docs/visualization/plotting-2d-data.ipynb
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot_1d.py
  python/src/scipp/plot/plot_2d.py
  python/src/scipp/plot/plot_3d.py
  python/src/scipp/plot/slicer.py
  python/src/scipp/plot/tools.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_nd.py
  python/variable.cpp
  variable/rebin.cpp
  variable/test/rebin_test.cpp
Labels: visualization

#1234 Fix is_linspace
  common/include/scipp/common/numeric.h
  common/test/is_linspace_test.cpp
Labels: bug

#1233 Move collapse out of plot and make it into a free function
  docs/about/release-notes.rst
  docs/visualization/plotting-1d-data.ipynb
  python/src/scipp/__init__.py
  python/src/scipp/_utils/__init__.py
  python/src/scipp/_utils/collapse_and_slices.py
  python/src/scipp/_utils/is_type.py
  python/src/scipp/_utils/to_string.py
  python/src/scipp/compat/mantid.py
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot_1d.py
  python/src/scipp/plot/plot_2d.py
  python/src/scipp/plot/plot_3d.py
  python/src/scipp/plot/slicer.py
  python/src/scipp/show.py
  python/src/scipp/table.py
  python/src/scipp/table_html/formatting_html.py
  python/tests/_utils/test_collapse_and_slices.py
  python/tests/_utils/test_to_string.py
Labels: python, visualization

#1236 To and from dict
  docs/python-reference/api.rst
  python/src/scipp/__init__.py
  python/src/scipp/compat/dict.py
  python/tests/compat/test_dict.py
Labels: python

#1237 Fix superplot when nans are present in values and variances
  python/src/scipp/plot/plot_1d.py
  python/tests/plot/test_plot_1d.py
Labels: bug, visualization

#1242 Add cppcheck to static analysis jobs
  .azure-pipelines/templates/code_quality_checks.yml
  tools/cppcheck.Dockerfile
Labels: CI

#1246 Add missing CSS causing bad formatting with (new) Sphinx theme.
  python/src/scipp/table_html/style.css
Labels: bug, docs

#1248 Properly fix CSS, with increases specificy
  python/src/scipp/table_html/style.css
Labels: bug, docs

#1243 New 3d plotting and new instrument view
  conda/meta.yaml
  docs/developer/dependencies.rst
  docs/scipp-neutron/instrument-view.ipynb
  docs/visualization/plotting-nd-data.ipynb
  python/src/scipp/_utils/__init__.py
  python/src/scipp/_utils/events.py
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/dispatch.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot_3d.py
  python/src/scipp/plot/render.py
  python/src/scipp/plot/slicer.py
  python/tests/neutron/test_neutron.py
  python/tests/plot/test_plot_nd.py
  scipp-developer-no-mantid.yml
  scipp-developer.yml
  scipp-jupyter-demo.Dockerfile
Labels: visualization
