Repository scipp/scipp, pull requests merged in 2020-06, with the labels that each got.

#1172 Add _repr_html_ for scipp, listing contents of %who <scipp obj>
  python/CMakeLists.txt
  python/src/scipp/__init__.py
  python/src/scipp/object_list.py
Labels: visualization

#1174 Exclude googlebenchmark from all so it does not end up in conda pkg
  CMake/GoogleBenchmark.cmake
Labels: CI

#1175 Add short page defining scipp's scope
  docs/about/contributing.rst
Labels: docs

#1173 Add choose
  dataset/CMakeLists.txt
  dataset/groupby.cpp
  dataset/include/scipp/dataset/choose.h
  dataset/shape.cpp
  dataset/test/CMakeLists.txt
  dataset/test/choose_test.cpp
  dataset/test/concatenate_test.cpp
  docs/python-reference/api.rst
  python/CMakeLists.txt
  python/choose.cpp
  python/scipp.cpp
Labels: LoKI

#1177 Add -p to mkdir in case dir already exists
  .azure-pipelines/pull_request.yml
  .azure-pipelines/templates/documentation_build.yml
Labels: CI, bug

#1170 Updates dtype error to tell users which numpy types we can take
  python/dtype.cpp
Labels: docs, priority:low, python

#1171 Handle single spec in to_workspace_2d
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
Labels: enhancement, python

#1188 Docs update
  .clang-format
  benchmark/dataset_operations_benchmark.cpp
  benchmark/element_array_view_benchmark.cpp
  core/test/element_util_test.cpp
  dataset/dataset.cpp
  dataset/groupby.cpp
  dataset/test/groupby_test.cpp
  dataset/test/rebin_test.cpp
  docs/about/about.rst
  docs/about/contributing.rst
  docs/about/release-notes.rst
  docs/developer/coding-conventions.rst
  docs/developer/getting-started.rst
  docs/developer/transform.rst
  docs/index.rst
  docs/user-guide/data-structures.ipynb
  docs/user-guide/tips-tricks-and-anti-patterns.ipynb
  neutron/test/convert_test.cpp
  python/bind_slice_methods.h
  python/detail.cpp
  python/eigen.cpp
  python/geometry.cpp
  variable/test/transform_test.cpp
Labels: docs

#1191 Fix segfault for value access with shape mismatch
  python/bind_data_access.h
  python/tests/test_variable.py
Labels: bug

#1194 Adds helper function to directly convert a var to Mantid WS
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
Labels: enhancement, python

#1193 Update to_string and _repr_html_ to handle unaligned content
  dataset/string.cpp
  python/src/scipp/table_html/formatting_html.py
Labels: visualization

#1208 Mantid compat updates
  docs/scipp-neutron/overview.rst
  python/src/scipp/compat/mantid.py
  python/src/scipp/neutron/__init__.py
  python/src/scipp/neutron/instrument_view.py
  python/tests/compat/test_mantid.py
Labels: LoKI, python

#1206 Concatenate with VariableConstView inputs requiring broadcast
  variable/include/scipp/variable/variable.tcc
  variable/test/operations_test.cpp
Labels: bug

#1212 Instrument view: Fix pixel size and add related missing Python binding
  docs/python-reference/api.rst
  python/groupby.cpp
  python/src/scipp/neutron/instrument_view.py
Labels: LoKI, bug

#1216 Remove Quaterniond and use Matrix3d
  core/include/scipp/core/element/arithmetic.h
  core/include/scipp/core/element/geometric_operations.h
  core/include/scipp/core/string.h
  core/test/element_geometric_operations_test.cpp
  python/bind_data_access.h
  python/eigen.cpp
  python/element_array_view.cpp
  python/geometry.cpp
  python/make_variable.h
  python/src/scipp/compat/mantid.py
  python/src/scipp/neutron/instrument_view.py
  python/tests/compat/test_mantid.py
  python/tests/test_eigen.py
  python/tests/test_variable.py
  python/variable.cpp
  variable/include/scipp/variable/misc_operations.h
  variable/include/scipp/variable/transform.h
  variable/include/scipp/variable/variable.h
  variable/include/scipp/variable/variable.tcc
  variable/operations.cpp
  variable/string.cpp
  variable/test/operations_test.cpp
  variable/test/transform_test.cpp
  variable/variable_instantiate_basic.cpp
Labels: bug

#1215 Add support for variables with variances in comparisons
  core/include/scipp/core/element/comparison.h
  core/include/scipp/core/value_and_variance.h
  core/test/element_comparison_test.cpp
  core/test/value_and_variance_test.cpp
  docs/python-reference/api.rst
  python/comparison.cpp
Labels: enhancement

#1204 Adds missing operators for Variables and int scalars
  python/tests/test_variable.py
  python/variable.cpp
Labels: python

#1223 Fix comparison with variances and add "values" and "variances" helpers
  core/include/scipp/core/element/comparison.h
  core/include/scipp/core/element/util.h
  core/include/scipp/core/transform_common.h
  core/test/element_util_test.cpp
  docs/python-reference/api.rst
  python/operations.cpp
  python/tests/test_variable.py
  variable/include/scipp/variable/transform.h
  variable/include/scipp/variable/util.h
  variable/test/comparison_test.cpp
  variable/test/transform_test.cpp
  variable/test/util_test.cpp
  variable/util.cpp
Labels: bug, enhancement
