Repository scipp/scipp, pull requests merged in 2020-05, with the labels that each got.

#1096 Dataset slice python refactor
  python/tests/conftest.py
  python/tests/test_data_array.py
  python/tests/test_dataset_slice.py
  python/tests/test_datasetslice.py
Labels: python, tests

#1095 CI refactor
  .azure-pipelines/pull_request.yml
  .azure-pipelines/templates/documentation_build.yml
  conda/bld.bat
  conda/build.sh
  conda/meta.yaml
  docs/developer/dependencies.rst
  docs/developer/getting-started.rst
  docs/environment.yml
  python/tests/compat/test_mantid.py
  scipp-developer-no-mantid.yml
  scipp-developer.yml
Labels: CI

#1121 Fix mantid compat validate unit rejecting correct inputs
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
Labels: bug, python

#1118 Python bindings cleanup
  benchmark/histogram_benchmark.cpp
  dataset/histogram.cpp
  dataset/include/scipp/dataset/dataset.h
  dataset/include/scipp/dataset/histogram.h
  python/CMakeLists.txt
  python/comparison.cpp
  python/dataset.cpp
  python/demo/demo-part0-Mantid-introduction.ipynb
  python/demo/demo-part3-final-exercise-solution.ipynb
  python/demo/img/1280px-NumPy_logo.png
  python/demo/img/1280px-Pandas_logo.png
  python/demo/img/WorkspaceHierarchy.jpg
  python/demo/img/cumulative-algorithm-count.png
  python/demo/img/dataset-3d-two-data-variables.png
  python/demo/img/dataset-diagram-logo.png
  python/demo/img/google-trends.png
  python/demo/img/sans-limitation.png
  python/docstring.cpp
  python/docstring.h
  python/geometry.cpp
  python/groupby.cpp
  python/histogram.cpp
  python/make_variable.h
  python/operations.cpp
  python/reduction.cpp
  python/scipp.cpp
  python/setup.py
  python/tests/test_variable.py
  python/trigonometry.cpp
  python/unary.cpp
  python/variable.cpp
  python/view.h
  variable/include/scipp/variable/misc_operations.h
  variable/include/scipp/variable/trigonometry.h
  variable/operations.cpp
  variable/trigonometry.cpp
Labels: python

#1117 Groupby with variable
  dataset/dataset.cpp
  dataset/groupby.cpp
  dataset/include/scipp/dataset/dataset.h
  dataset/include/scipp/dataset/groupby.h
  dataset/test/dataset_test.cpp
  dataset/test/groupby_test.cpp
  docs/user-guide/groupby.ipynb
  python/groupby.cpp
Labels: enhancement, good first issue

#1129 Missing spaces after `op` in docstrings.
  python/comparison.cpp
  python/groupby.cpp
  python/trigonometry.cpp
Labels: docs

#1131 Fix broken Docker build
  scipp-jupyter-demo.Dockerfile
Labels: CI

#1128 Fixes for loading loki files
  python/src/scipp/compat/mantid.py
Labels: LoKI

#1122 CI tidy
  .azure-pipelines/pull_request.yml
  .azure-pipelines/release.yml
  .azure-pipelines/templates/code_quality_checks.yml
  .azure-pipelines/templates/documentation_build.yml
  .azure-pipelines/templates/documentation_deploy.yml
Labels: CI

#1127 Test cleanup
  core/CMakeLists.txt
  core/include/scipp/core/element/histogram.h
  core/test/CMakeLists.txt
  core/test/element_histogram_test.cpp
  dataset/groupby.cpp
  dataset/histogram.cpp
  dataset/test/CMakeLists.txt
  dataset/test/masks_view_test.cpp
  neutron/convert.cpp
  neutron/include/scipp/neutron/constants.h
  neutron/include/scipp/neutron/conversions.h
  neutron/test/CMakeLists.txt
  neutron/test/constants_test.cpp
  neutron/test/conversions_test.cpp
Labels: tests

#1135 Sort coords/masks/attrs alphabetically when displayed
  dataset/string.cpp
  python/src/scipp/table_html/formatting_html.py
  python/tests/table_html/test_to_html_dataarray.py
  python/tests/table_html/test_to_html_dataset.py
Labels: visualization

#1136 Further CI improvments
  .azure-pipelines/pull_request.yml
Labels: CI

#1139 Skip geometry conversion via keyword argument
  docs/scipp-neutron/instrument-view.ipynb
  python/src/scipp/compat/mantid.py
Labels: neutron

#1140 Use Mantid's extractY() and extractE() for 2D data
  python/bind_data_access.h
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
Labels: neutron

#1146 Added __rtruediv__ for Variable. #1141
  python/tests/test_variable.py
  python/variable.cpp
Labels: bug

#1142 Add docstring for new advanced_geometry argument in Mantid compat
  python/src/scipp/compat/mantid.py
Labels: docs

#1154 Speed up MSVC Compilation
  CMake/IPO.cmake
  CMakeLists.txt
  docs/developer/tooling.rst
Labels: CI, core

#1152 Collection of misc fixes
  docs/data/fetch_neutron_data.py
  docs/developer/getting-started.rst
  python/src/scipp/compat/mantid.py
Labels: CI, docs, python

#1147 Add test for groupby.sum with realigned data and masks
  dataset/test/groupby_test.cpp
Labels: tests

#1159 Help update with VC redistributable link
  docs/getting-started/faq.rst
  docs/getting-started/installation.rst
Labels: docs

#1158 Fix groupby.sum with 2D coords
  dataset/dataset_operations_common.h
  dataset/include/scipp/dataset/map_view.h
  dataset/operations.cpp
  dataset/test/groupby_test.cpp
Labels: bug, dream

#1151 Handle special FP vals in masks
  core/include/scipp/core/element/util.h
  core/test/CMakeLists.txt
  core/test/element_util_test.cpp
  dataset/test/sum_test.cpp
  dataset/variable_reduction.cpp
  docs/developer/transform.rst
Labels: bug, core

#1160 Add realign option to neutron.convert
  core/include/scipp/core/except.h
  dataset/dataset_operations_common.h
  dataset/event.cpp
  dataset/histogram.cpp
  neutron/convert.cpp
  neutron/include/scipp/neutron/convert.h
  neutron/test/convert_test.cpp
  python/neutron.cpp
  python/tests/compat/test_mantid.py
  python/tests/neutron/test_neutron.py
  variable/CMakeLists.txt
  variable/include/scipp/variable/util.h
  variable/test/CMakeLists.txt
  variable/test/util_test.cpp
  variable/util.cpp
Labels: dream, neutron

#1162 Less restrictive logic in subspan_view to avoid need for copies
  variable/subspan_view.cpp
Labels: LoKI

#1166 Coerce spectrum float64 to int64 for spectrum coord
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
Labels: bug

#1167 Add tips and tricks doc page
  docs/index.rst
  docs/user-guide/tips-tricks-and-anti-patterns.ipynb
  docs/user-guide/unaligned-data.ipynb
Labels: docs
