Repository scipp/scipp, pull requests merged in 2020-12, with the labels that each got.

#1426 Add check to prevent bad rebin if there are unaligned (2d) bins
  core/dimensions.cpp
  dataset/bin.cpp
  dataset/test/bin_test.cpp
Labels: bug

#1429 Fix log norm update for 1d and 2d figures
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/figure2d.py
Labels: bug, visualization

#1439 Remove docker deploy step
  .azure-pipelines/master.yml
Labels: CI

#1447 Support data without variances in `histogram`
  core/include/scipp/core/element/histogram.h
  core/test/element_histogram_test.cpp
  dataset/test/bin_test.cpp
  dataset/test/dataset_test_common.cpp
  dataset/test/dataset_test_common.h
  dataset/test/histogram_test.cpp
  variable/subspan_view.cpp
  variable/test/subspan_view_test.cpp
Labels: bug

#1456 Avoid copies in plots
  docs/visualization/plotting-2d-data.ipynb
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller1d.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/helpers.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model1d.py
  python/src/scipp/plot/model2d.py
  python/src/scipp/plot/model3d.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/plot1d.py
  python/src/scipp/plot/plot2d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/profile.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/view.py
  python/src/scipp/plot/view2d.py
  python/src/scipp/plot/widgets.py
  python/tests/plot/plot_helper.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_array.py
  python/variable.cpp
Labels: visualization

#1459 Plot method on scipp objects
  docs/about/release-notes.rst
  docs/visualization/plotting-overview.ipynb
  python/src/scipp/__init__.py
  python/tests/plot/test_plot_methods.py
Labels: visualization

#1461 Check if dim exists in coords before setting underlying_dim
  python/src/scipp/plot/sciplot.py
  python/tests/plot/test_plot_nd.py
Labels: bug, visualization

#1463 Use attrs for plot axes
  python/src/scipp/plot/model.py
  python/src/scipp/plot/sciplot.py
  python/tests/plot/plot_helper.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_nd.py
Labels: bug, visualization

#1460 Wrap 3d renderer in widget to prevent toolbar from being hidden
  python/src/scipp/plot/figure3d.py
Labels: bug, visualization

#1464 Small plotting cleanup
  docs/visualization/customizing-figures.ipynb
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/helpers.py
  python/src/scipp/plot/plot.py
  python/src/scipp/plot/sciplot.py
  python/tests/plot/test_plot_1d.py
  python/tests/plot/test_plot_2d.py
Labels: visualization

#1470 Remove non-dimension positions dim in slider dim buttons for instrument view
  python/src/scipp/plot/widgets.py
Labels: bug, visualization

#1475 Fix neutron unit conversion for slices of data arrays
  neutron/convert.cpp
  neutron/test/convert_test.cpp
Labels: bug, neutron

#1474 Note the license for each direct dependency
  docs/developer/dependencies.rst
Labels: docs

#1482 Fix compat tests
  python/tests/compat/test_mantid.py
Labels: bug

#1481 Scale binned slice
  dataset/test/CMakeLists.txt
  dataset/test/binned_arithmetic_test.cpp
  dataset/variable_instantiate_bucket_elements.cpp
  variable/include/scipp/variable/bucket_variable.tcc
  variable/include/scipp/variable/transform.h
  variable/include/scipp/variable/variable_factory.h
  variable/variable_factory.cpp
Labels: bug

#1468 On-the-fly resample of binned data.
  common/include/scipp/common/numeric.h
  core/include/scipp/core/dimensions.h
  core/include/scipp/core/element/bin.h
  core/include/scipp/core/element/comparison.h
  dataset/bin.cpp
  dataset/include/scipp/dataset/bin.h
  dataset/include/scipp/dataset/bins_view.h
  dataset/include/scipp/dataset/map_view.h
  dataset/map_view.cpp
  dataset/slice.cpp
  dataset/test/bin_test.cpp
  dataset/test/groupby_test.cpp
  dataset/test/slice_by_value_test.cpp
  dataset/variable_reduction.cpp
  docs/tutorials/neutron-diffraction.ipynb
  docs/user-guide/binned-data/binned-data.ipynb
  docs/user-guide/slicing.ipynb
  python/bins.cpp
  python/operations.cpp
  python/src/scipp/plot/dispatch.py
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/helpers.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model1d.py
  python/src/scipp/plot/model2d.py
  python/src/scipp/plot/model3d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/resampling_model.py
  python/tests/plot/plot_helper.py
  python/tests/plot/test_plot_array.py
  variable/CMakeLists.txt
  variable/include/scipp/variable/slice.h
  variable/rebin.cpp
  variable/slice.cpp
Labels: visualization

#1487 Fix lost vmin and vmax on toggle norm
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller1d.py
  python/src/scipp/plot/figure1d.py
Labels: bug, visualization
