Repository scipp/scipp, pull requests merged in 2021-01, with the labels that each got.

#1507 Version selection menu in docs
  docs/_static/favicon.ico
  docs/_templates/layout.html
  docs/conf.py
  docs/getting-started/overview.rst
  docs/python-reference/api.rst
Labels: docs

#1510 Mark bin-edges of attributes in HTML repr
  dataset/string.cpp
  python/src/scipp/table_html/formatting_html.py
  variable/string.cpp
Labels: bug, visualization

#1511 Update string representations
  dataset/string.cpp
  variable/string.cpp
Labels: visualization

#1505 Fix sliceviewer performance issue and broken profile plot
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model2d.py
  python/src/scipp/plot/resampling_model.py
Labels: bug, optimisation, visualization

#1495 Fix cursor hover values with masks in 2d image plots
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller1d.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model2d.py
  python/src/scipp/plot/model3d.py
  python/src/scipp/plot/tools.py
  python/src/scipp/plot/view.py
  python/src/scipp/plot/view2d.py
Labels: bug, visualization

#1509 Hide profile plot axes in docs
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/helpers.py
  python/src/scipp/plot/profile.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/view.py
Labels: docs, visualization

#1530 Remove double definition of options
  python/dataset.cpp
Labels: bug

#1529 Reduction performance bug
  benchmark/transform_benchmark.cpp
  core/dimensions.cpp
  core/test/dimensions_test.cpp
Labels: bug, optimisation

#1531 Fix value access when using value based cut surface in 3d plots
  python/src/scipp/plot/model3d.py
Labels: bug, visualization

#1532 Disable sliders when dim has length 1
  python/src/scipp/plot/widgets.py
Labels: visualization

#1500 Bin arg validation
  dataset/bin.cpp
  dataset/test/bin_test.cpp
Labels: bug

#1525 Better handling for non-dimension coordinates in plots
  python/src/scipp/plot/model.py
Labels: bug, visualization

#1533 Fix small instrument view issues
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/panel3d.py
  python/src/scipp/plot/plot3d.py
Labels: visualization

#1543 Multi-resolution favicon
  docs/_static/favicon.ico
Labels: docs

#1538 Fix mandatory tbb dependency
  core/CMakeLists.txt
  dataset/CMakeLists.txt
  variable/CMakeLists.txt
Labels: bug

#1540 Prevent bin data use with rebin
  variable/include/scipp/variable/bucket_variable.tcc
  variable/rebin.cpp
  variable/test/rebin_test.cpp
Labels: bug

#1545 Include tcc files in clang-format applied file search
  .azure-pipelines/templates/code_quality_checks.yml
Labels: CI

#1542 Fix small issues in User Guide
  dataset/dataset.cpp
  docs/python-reference/error-propagation.rst
  docs/user-guide/binned-data/binned-data.ipynb
  docs/user-guide/binned-data/computation.ipynb
  docs/user-guide/binned-data/filtering.ipynb
  docs/user-guide/binned-data/histogramming-grouping-and-binning.ipynb
  docs/user-guide/computation.ipynb
  docs/user-guide/data-structures.ipynb
  docs/user-guide/groupby.ipynb
  docs/user-guide/how_to.ipynb
  docs/user-guide/reading-and-writing-files.ipynb
  docs/user-guide/slicing.ipynb
  docs/user-guide/tips-tricks-and-anti-patterns.ipynb
Labels: docs

#1539 Optimise non-in-place transforms using special cases for strides
  variable/include/scipp/variable/transform.h
Labels: optimisation

#1537 Improvements for 3D plotting (including instrument view)
  docs/scipp-neutron/instrument-view.ipynb
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/figure.py
  python/src/scipp/plot/figure1d.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/model3d.py
  python/src/scipp/plot/panel3d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/tools.py
  python/tests/plot/test_plot_2d.py
  python/tests/plot/test_plot_3d.py
Labels: visualization

#1548 Simplify handling of binned data in unit conversion
  neutron/convert.cpp
Labels: neutron

#1551 Check volume in reshape
  variable/include/scipp/variable/shape.h
  variable/shape.cpp
  variable/test/shape_test.cpp
  variable/test/variable_test.cpp
  variable/variable.cpp
Labels: bug

#1553 Better behaviour for using autoscale in combination with log norm
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller2d.py
  python/src/scipp/plot/figure2d.py
  python/src/scipp/plot/model.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/tools.py
  python/src/scipp/plot/view2d.py
  python/tests/plot/test_plot_2d.py
Labels: bug, visualization

#1562 Fixes a crash when making empty Variables
  core/include/scipp/core/view_index.h
  core/test/view_index_test.cpp
  core/view_index.cpp
  python/make_variable.h
  python/numpy.h
Labels: bug

#1565 Avoid division by zero in `__sizeof__`
  dataset/test/size_of_test.cpp
  dataset/util.cpp
Labels: bug

#1561 Tweaks for instrument view
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plot/controller.py
  python/src/scipp/plot/controller3d.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/model3d.py
  python/src/scipp/plot/toolbar.py
  python/src/scipp/plot/tools.py
Labels: visualization

#1571 Get pixel ratio of device from running javascript command in ipykernel
  docs/scipp-neutron/instrument-view.ipynb
  python/src/scipp/plot/__init__.py
  python/src/scipp/plot/figure3d.py
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/toolbar.py
Labels: visualization

#1576 Reduction zero dimension extent fixes
  core/include/scipp/core/element/creation.h
  core/include/scipp/core/element_array_view.h
  variable/creation.cpp
  variable/include/scipp/variable/creation.h
  variable/reduction.cpp
  variable/test/CMakeLists.txt
  variable/test/creation_test.cpp
  variable/test/mean_test.cpp
  variable/test/operations_test.cpp
  variable/test/reduce_logical_test.cpp
  variable/test/reduce_various_test.cpp
  variable/test/sum_test.cpp
  variable/test/test_variables.cpp
Labels: bug

#1579 Binned plot fixed for inner dimension without event coord
  python/src/scipp/plot/resampling_model.py
  python/tests/plot/test_plot_2d.py
Labels: bug

#1583 Fix infinite loop when zooming on empty bins
  core/include/scipp/core/multi_index.h
  core/test/multi_index_test.cpp
  dataset/bin.cpp
  dataset/test/bin_test.cpp
  dataset/test/bins_test.cpp
  variable/include/scipp/variable/bucket_variable.tcc
Labels: bug

#1582 Fix segault from bad GIL release
  python/bins.cpp
Labels: bug

#1587 Safely update slider bounds in all cases for cut surface
  python/src/scipp/plot/panel3d.py
Labels: bug, visualization

#1585 Extra fixes for empty dims
  dataset/bins.cpp
  dataset/test/concatenate_test.cpp
  variable/include/scipp/variable/bucket_model.h
  variable/reduction.cpp
Labels: bug

#1593 Tiny fixes in neutron docs
  docs/scipp-neutron/groupby.ipynb
  docs/scipp-neutron/overview.rst
  python/src/scipp/compat/mantid.py
Labels: docs

#1601 Html repr cleanup for binned data
  python/src/scipp/table_html/formatting_html.py
Labels: visualization

#1626 Add 0.5 in docs version menu
  docs/_templates/layout.html
Labels: docs

#1628 Wrappers not returning
  python/src/scipp/_unary.py
Labels: bug
