Repository scipp/scipp, pull requests merged in 2021-02, with the labels that each got.

#1637 Support binning data with column dtype Eigen::Vector3d
  variable/subspan_view.cpp
Labels: bug

#1635 Inelastic unit conversions
  docs/index.rst
  docs/scipp-neutron/overview.rst
  docs/scipp-neutron/unit-conversions.ipynb
  neutron/beamline.cpp
  neutron/convert.cpp
  neutron/include/scipp/neutron/beamline.h
  neutron/include/scipp/neutron/constants.h
  neutron/include/scipp/neutron/conversions.h
  neutron/include/scipp/neutron/convert.h
  neutron/test/constants_test.cpp
  neutron/test/conversions_test.cpp
  neutron/test/convert_test.cpp
  python/src/scipp/compat/mantid.py
  python/tests/compat/test_mantid.py
  test/test_macros.h
  units/dim.cpp
  units/include/scipp/units/dim.h
Labels: neutron

#1669 Rename master branch to `main`
  .azure-pipelines/main.yml
  .azure-pipelines/weekly_tasks.yml
  README.md
  conda/README.md
  docs/developer/dependencies.rst
  docs/developer/deployment.rst
  docs/scipp-neutron/groupby.ipynb
Labels: CI

#1679 Fix equation in docs
  docs/scipp-neutron/unit-conversions.ipynb
Labels: docs

#1689 Add matrix_3_float64 to hdf5 io
  python/src/scipp/io/hdf5.py
  python/tests/io/test_hdf5.py
Labels: python

#1681 Fix instrument view with 2(+)d positions coordinate
  python/src/scipp/plot/plot3d.py
  python/src/scipp/plot/sciplot.py
  python/src/scipp/plot/widgets.py
  python/tests/plot/test_plot_3d.py
Labels: bug, visualization

#1696 Rename plot module to plotting
  docs/conf.py
  docs/getting-started/quick-start.ipynb
  docs/python-reference/api.rst
  docs/scipp-neutron/groupby.ipynb
  docs/tutorials/introduction.ipynb
  docs/tutorials/multi-d-datasets.ipynb
  docs/tutorials/neutron-diffraction.ipynb
  docs/user-guide/binned-data/binned-data.ipynb
  docs/user-guide/binned-data/computation.ipynb
  docs/user-guide/binned-data/filtering.ipynb
  docs/user-guide/binned-data/histogramming-grouping-and-binning.ipynb
  docs/user-guide/groupby.ipynb
  docs/visualization/customizing-figures.ipynb
  docs/visualization/plotting-1d-data.ipynb
  docs/visualization/plotting-2d-data.ipynb
  docs/visualization/plotting-nd-data.ipynb
  docs/visualization/plotting-overview.ipynb
  python/CMakeLists.txt
  python/src/scipp/__init__.py
  python/src/scipp/neutron/instrument_view.py
  python/src/scipp/plotting/__init__.py
  python/src/scipp/plotting/controller.py
  python/src/scipp/plotting/controller1d.py
  python/src/scipp/plotting/controller2d.py
  python/src/scipp/plotting/controller3d.py
  python/src/scipp/plotting/dispatch.py
  python/src/scipp/plotting/figure.py
  python/src/scipp/plotting/figure1d.py
  python/src/scipp/plotting/figure2d.py
  python/src/scipp/plotting/figure3d.py
  python/src/scipp/plotting/helpers.py
  python/src/scipp/plotting/model.py
  python/src/scipp/plotting/model1d.py
  python/src/scipp/plotting/model2d.py
  python/src/scipp/plotting/model3d.py
  python/src/scipp/plotting/panel.py
  python/src/scipp/plotting/panel1d.py
  python/src/scipp/plotting/panel3d.py
  python/src/scipp/plotting/plot.py
  python/src/scipp/plotting/plot1d.py
  python/src/scipp/plotting/plot2d.py
  python/src/scipp/plotting/plot3d.py
  python/src/scipp/plotting/profile.py
  python/src/scipp/plotting/resampling_model.py
  python/src/scipp/plotting/sciplot.py
  python/src/scipp/plotting/toolbar.py
  python/src/scipp/plotting/tools.py
  python/src/scipp/plotting/view.py
  python/src/scipp/plotting/view1d.py
  python/src/scipp/plotting/view2d.py
  python/src/scipp/plotting/view3d.py
  python/src/scipp/plotting/widgets.py
  python/tests/plotting/plot_helper.py
  python/tests/plotting/test_plot_0d.py
  python/tests/plotting/test_plot_1d.py
  python/tests/plotting/test_plot_2d.py
  python/tests/plotting/test_plot_3d.py
  python/tests/plotting/test_plot_array.py
  python/tests/plotting/test_plot_methods.py
  python/tests/plotting/test_plot_nd.py
Labels: visualization

#1699 Remove annoying javascript error when reloading notebook
  docs/about/release-notes.rst
  python/src/scipp/plotting/__init__.py
Labels: visualization

#1703 Use matplotlib-base to avoid pulling in Qt during CI
  conda/meta.yaml
  scipp-developer-no-mantid.yml
  scipp-developer.yml
Labels: CI

#1707 Setup cmake package
  CMake/scipp-config.cmake.in
  CMake/scipp-functions.cmake
  CMake/scipp-install.cmake
  CMake/scipp-util.cmake
  CMakeLists.txt
  common/CMakeLists.txt
  core/CMakeLists.txt
  dataset/CMakeLists.txt
  neutron/CMakeLists.txt
  units/CMakeLists.txt
  variable/CMakeLists.txt
Labels: CI

#1710 Fix bad overload selection caused by implicit conversion
  python/tests/test_variable.py
  python/variable.cpp
Labels: bug, python

#1695 Escape user strings
  python/src/scipp/plotting/widgets.py
  python/src/scipp/show.py
  python/src/scipp/table.py
  python/src/scipp/table_html/formatting_html.py
Labels: visualization

#1723 Remove data fetcher and mantid setup from docs build
  .azure-pipelines/templates/documentation_build.yml
  cmake/docs_build.sh.in
Labels: docs
