Repository scipp/scipp, pull requests merged in 2021-05, with the labels that each got.

#1892 Docs structure
  docs/index.rst
  docs/python-reference/units.ipynb
  docs/user-guide/reading-and-writing-files.ipynb
  docs/visualization/plotting-in-depth.rst
  docs/visualization/plotting/customizing-figures.ipynb
  docs/visualization/plotting/datetime_handling.ipynb
  docs/visualization/plotting/plotting-1d-data.ipynb
  docs/visualization/plotting/plotting-2d-data.ipynb
  docs/visualization/plotting/plotting-nd-data.ipynb
Labels: docs

#1906 Fix move includes in packaging for windows
  conda/bld.bat
Labels: bug

#1920 Remove old javascript code for devicePixelRatio which does not work in Lab
  docs/reference/runtime-configuration.ipynb
  docs/user-guide/data-structures.ipynb
  docs/user-guide/slicing.ipynb
  python/src/scipp/plotting/__init__.py
  python/src/scipp/plotting/plot3d.py
  python/src/scipp/runtime_config.py
Labels: visualization

#1921 Fix two issues with nanmean
  dataset/reduction.cpp
  variable/operations_common.h
  variable/reduction.cpp
  variable/test/mean_test.cpp
Labels: bug

#1924 Avoid read-only problem in comparision for structured (matrix) dtypes
  variable/include/scipp/variable/structure_array_model.h
Labels: bug

#1930 Various cleanup and small fix
  core/include/scipp/core/flags.h
  dataset/bins.cpp
  dataset/groupby.cpp
  dataset/include/scipp/dataset/bins.h
  dataset/include/scipp/dataset/groupby.h
  dataset/include/scipp/dataset/shape.h
  dataset/include/scipp/dataset/sort.h
  dataset/shape.cpp
  dataset/sort.cpp
  dataset/test/groupby_test.cpp
  python/bind_data_access.h
  python/variable.cpp
  units/dim.cpp
  units/include/scipp/units/dim.h
  variable/bins.cpp
  variable/creation.cpp
  variable/include/scipp/variable/creation.h
  variable/include/scipp/variable/shape.h
  variable/include/scipp/variable/sort.h
  variable/include/scipp/variable/structure_array_variable.tcc
  variable/include/scipp/variable/util.h
  variable/shape.cpp
  variable/test/creation_test.cpp
  variable/test/linalg_test.cpp
  variable/test/operations_test.cpp
  variable/test/variable_structure_test.cpp
Labels: bug

#1931 Fix multiple lines in projection=1d
  python/src/scipp/plotting/plot.py
  python/tests/plotting/test_plot_1d.py
Labels: bug, visualization

#1933 Fix HTML repr fails with bin edge coords
  python/src/scipp/html/formatting_html.py
Labels: bug

#1940 Plot: check for ill-formed inputs with multi-dimensional coords
  python/src/scipp/plotting/objects.py
  python/tests/plotting/test_plot_2d.py
Labels: bug, visualization

#1946 Temporarily disable windows builds
  .azure-pipelines/main.yml
  .azure-pipelines/pull_request.yml
  .azure-pipelines/release.yml
Labels: CI
