Repository scipp/scipp, pull requests merged in 2021-03, with the labels that each got.

#1724 Add under and over colors in masks cmap
  python/src/scipp/plotting/sciplot.py
  python/src/scipp/plotting/tools.py
Labels: visualization

#1727 Binned op checks
  dataset/CMakeLists.txt
  dataset/test/binned_arithmetic_test.cpp
  dataset/variable_instantiate_bin_elements.cpp
  python/tests/plotting/test_plot_2d.py
  variable/include/scipp/variable/bin_variable.tcc
  variable/include/scipp/variable/variable_factory.h
  variable/variable_factory.cpp
  variable/variable_instantiate_bin_elements.cpp
Labels: bug

#1778 Improve and update build instructions
  docs/developer/getting-started.rst
Labels: docs

#1777 Plot datetime by converting coordinate to integers
  docs/index.rst
  docs/visualization/datetime_handling.ipynb
  docs/visualization/plotting-1d-data.ipynb
  python/numpy.h
  python/src/scipp/plotting/controller.py
  python/src/scipp/plotting/controller1d.py
  python/src/scipp/plotting/figure.py
  python/src/scipp/plotting/figure1d.py
  python/src/scipp/plotting/formatters.py
  python/src/scipp/plotting/model.py
  python/src/scipp/plotting/model1d.py
  python/src/scipp/plotting/view.py
  python/tests/plotting/test_plot_1d.py
  python/tests/plotting/test_plot_2d.py
  variable/include/scipp/variable/variable.h
Labels: visualization

#1790 Add legend control kwarg in 1d plots
  docs/about/release-notes.rst
  python/src/scipp/plotting/figure1d.py
  python/src/scipp/plotting/plot1d.py
  python/tests/plotting/test_plot_1d.py
Labels: visualization

#1795 Kill zombie colorbar
  python/src/scipp/plotting/figure3d.py
  python/src/scipp/plotting/sciplot.py
Labels: bug, visualization

#1799 Ignore inputs of dtype vector and string in plot
  python/src/scipp/__init__.py
  python/src/scipp/_utils/__init__.py
  python/src/scipp/_utils/typing.py
  python/src/scipp/plotting/model.py
  python/src/scipp/plotting/plot.py
Labels: visualization

#1803 Ignore empty variables in plots
  python/src/scipp/plotting/plot.py
Labels: visualization
