Repository scipp/scipp, pull requests merged in 2021-04, with the labels that each got.

#1800 Add close method to plots
  python/src/scipp/plotting/__init__.py
  python/src/scipp/plotting/figure.py
  python/src/scipp/plotting/figure3d.py
  python/src/scipp/plotting/helpers.py
  python/src/scipp/plotting/sciplot.py
  python/src/scipp/plotting/tools.py
  python/src/scipp/plotting/view.py
  python/src/scipp/plotting/view3d.py
Labels: visualization

#1809 Fix bug in limits of 1d plots when more than 1 entry is on the same axes
  python/src/scipp/plotting/controller.py
Labels: bug, visualization

#1810 Pin docutils to 0.16
  scipp-developer.yml
Labels: docs

#1827 Cannot import scipp after building on rhel7
  python/CMakeLists.txt
Labels: bug

#1725 Cleanup azure
  .azure-pipelines/main.yml
  .azure-pipelines/pull_request.yml
  .azure-pipelines/release.yml
  .azure-pipelines/templates/build.yml
  .azure-pipelines/templates/ccache.yml
  .azure-pipelines/templates/code_quality_checks.yml
  .azure-pipelines/templates/deploy.yml
  .azure-pipelines/templates/documentation.yml
  .azure-pipelines/templates/documentation_build.yml
  .azure-pipelines/templates/documentation_deploy.yml
  .azure-pipelines/templates/stages.yml
  .azure-pipelines/templates/test_can_install_and_import.yml
  conda/bld.bat
  conda/build.sh
  conda/meta.yaml
  tools/make_and_install.bat
  tools/make_and_install.sh
Labels: CI

#1862 Add instructions on how to deploy docs pages to github pages
  docs/developer/deployment.rst
Labels: docs

#1858 Fix 1d y axis limits issues
  python/src/scipp/plotting/__init__.py
  python/src/scipp/plotting/controller1d.py
  python/src/scipp/plotting/figure.py
  python/src/scipp/plotting/figure1d.py
Labels: bug, visualization

#1864 Add `sc.zeros_like` and `sc.ones_like` functions
  docs/about/release-notes.rst
  docs/python-reference/api.rst
  python/src/scipp/_variable.py
  python/tests/test_variable_creation.py
Labels: python

#1869 Fix squeeze
  dataset/bin.cpp
  variable/include/scipp/variable/shape.h
  variable/shape.cpp
  variable/test/shape_test.cpp
Labels: bug

#1877 Copy bug
  dataset/dataset.cpp
  dataset/include/scipp/dataset/dataset.h
  dataset/operations.cpp
  dataset/test/concatenate_test.cpp
  dataset/test/copy_test.cpp
Labels: bug
