Repository scipp/scipp, pull requests merged in 2021-11, with the labels that each got.

#2262 Strip bin-edge coords in groupby.copy
  lib/dataset/dataset_operations_common.h
  lib/dataset/groupby.cpp
  lib/dataset/operations.cpp
  lib/dataset/test/groupby_test.cpp
Labels: bug

#2268 Move/remove old information from "What's new" page
  docs/about/whats-new.ipynb
  docs/index.rst
  docs/reference/ownership-mechanism-and-readonly-flags.ipynb
Labels: docs

#2265 Add toggle buttons for 3D RGB axes and outline box
  src/scipp/plotting/figure3d.py
  src/scipp/plotting/toolbar.py
Labels: visualization

#2269 Fix plotting with masks in presence of multi-dim coords
  src/scipp/plotting/resampling_model.py
  tests/plotting/plot_2d_test.py
Labels: bug, visualization

#2302 Fix broken `sc.bins` if indices are not ordered
  lib/dataset/bins.cpp
  lib/variable/bins.cpp
  lib/variable/include/scipp/variable/structure_array_model.h
  lib/variable/operations_common.h
  lib/variable/test/variable_bin_test.cpp
  lib/variable/test/variable_structure_test.cpp
  lib/variable/variable_instantiate_bin_elements.cpp
  tests/bins_test.py
Labels: bug
