Repository scipp/scipp, pull requests merged in 2022-11, with the labels that each got.

#2868 Update images in Scipp docs title page
  docs/_static/title-binning.png
  docs/_static/title-filtering-1d-plot.svg
  docs/_static/title-instrument-view.png
  docs/_static/title-masking.png
  docs/_static/title-plotting.png
  docs/_static/title-repr-html.png
  docs/_static/title-show-svg.png
  docs/_static/title-show.png
  docs/index.rst
Labels: docs

#2877 Allow redefining a unit alias as itself
  src/scipp/units/__init__.py
  tests/unit_test.py
Labels: bug

#2891 Minor release workflow fixes
  .github/workflows/release.yml
Labels: build system
