Repository scipp/scipp, pull requests merged in 2022-08, with the labels that each got.

#2738 Add docs/warnings about IPython output caching
  docs/getting-started/faq.rst
  docs/user-guide/data-structures.ipynb
  docs/visualization/representations-and-tables.ipynb
Labels: docs

#2748 Fix experimental plotting to accept DataArrays without coords
  docs/about/release-notes.rst
  src/scipp/experimental/plotting/__init__.py
  src/scipp/experimental/plotting/wrappers.py
  tests/experimental/plotting/graph_nodes_test.py
  tests/experimental/plotting/wrappers_test.py
Labels: experimental plotting

#2750 Fix setitem for value based slicing
  docs/about/release-notes.rst
  lib/python/bind_slice_methods.h
  tests/slice_test.py
Labels: bug

#2746 Fix profile plot
  docs/about/release-notes.rst
  src/scipp/plotting/profile.py
  src/scipp/plotting/view.py
  src/scipp/plotting/view2d.py
Labels: bug, visualization

#2760 Datetime `arange` fixes
  docs/user-guide/data-structures/creating-arrays-and-datasets.ipynb
  src/scipp/core/variable.py
  tests/variable_creation_test.py
Labels: bug

#2780 Fix and re-enable linkcheck on main
  .github/workflows/pr_and_main.yml
  docs/index.rst
Labels: build system

#2784 Remove unused workflow for removing old conda packages
  .github/workflows/weekly_tasks.yml
  README.md
  tools/anaconda_remove_old_dev_packages.sh
Labels: build system

#2791 Add test for checking if scipp can be imported with no extra dependencies
  .github/workflows/pr_and_main.yml
  tox.ini
Labels: build system

#2804 Ship scipp with conan cmake setup to simplify dependency install
  conda/cmake-package-test/CMakeLists.txt
  conda/cmake-package-test/conanfile.txt
  docs/reference/developer/dependencies.rst
  lib/CMakeLists.txt
  lib/cmake/.conan-recipes/llnl-units/conanfile.py
  lib/cmake/scipp-conan.cmake
  lib/cmake/scipp-config.cmake.in
Labels: build system

#2807 Change file name of plot function to avoid mix-up with module name when imported multiple times
  src/scipp/plotting/__init__.py
  src/scipp/plotting/wrapper.py
  tests/plotting/plot_import_test.py
Labels: bug
