Repository scipp/scipp, pull requests merged in 2022-01, with the labels that each got.

#2351 Switch to Thursday builds instead of nightly
  .github/workflows/package_nightly_and_release.yml
Labels: CI

#2355 Fix bug in `sc.bin` when rebinning to multi-dim coord
  docs/about/release-notes.rst
  lib/dataset/bin.cpp
  lib/dataset/test/bin_test.cpp
Labels: bug

#2379 Fix 'whats new'
  docs/about/release-notes.rst
  docs/about/whats-new.ipynb
Labels: docs

#2382 Add abs dunder method to Variable, DataArray, Dataset
  docs/about/release-notes.rst
  lib/python/bind_operators.h
  tests/variable_test.py
Labels: enhancement

#2381 Enable cppcheck on CI
  CMakePresets.json
  lib/CMakeLists.txt
  lib/python/bind_operators.h
  lib/python/dtype.cpp
  scipp-developer.yml
Labels: CI
